### ISSUE TITLE
MuQSS build failure.

### ISSUE THREAD

**Issue by Techwolf** [zen-kernel/zen-kernel#138] opened 2019-03-03 06:29 UTC
Kernel version 4.19.25 and 4.19.26 will fail to build if MuQSS is enabled.

```
  CC      kernel/sched/MuQSS.o
In file included from ./include/linux/linkage.h:7:0,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/cpumask.h:10,
                 from ./include/linux/sched/isolation.h:4,
                 from kernel/sched/MuQSS.c:34:
kernel/sched/MuQSS.c:230:19: error: ‘sched_smt_present’ undeclared here (not in a function); did you mean ‘sched_asym_prefer’?
 EXPORT_SYMBOL_GPL(sched_smt_present);
                   ^
./include/linux/export.h:79:16: note: in definition of macro ‘___EXPORT_SYMBOL’
  extern typeof(sym) sym;      \
                ^~~
kernel/sched/MuQSS.c:230:1: note: in expansion of macro ‘EXPORT_SYMBOL_GPL’
 EXPORT_SYMBOL_GPL(sched_smt_present);
 ^~~~~~~~~~~~~~~~~
In file included from ./arch/x86/include/asm/string_64.h:6:0,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from ./include/linux/bitmap.h:9,
                 from ./include/linux/cpumask.h:12,
                 from ./include/linux/sched/isolation.h:4,
                 from kernel/sched/MuQSS.c:34:
kernel/sched/MuQSS.c:1024:25: error: conflicting types for ‘sched_smt_present’
 DEFINE_STATIC_KEY_FALSE(sched_smt_present);
                         ^
./include/linux/jump_label.h:309:26: note: in definition of macro ‘DEFINE_STATIC_KEY_FALSE’
  struct static_key_false name = STATIC_KEY_FALSE_INIT
                          ^~~~
In file included from ./include/linux/linkage.h:7:0,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/cpumask.h:10,
                 from ./include/linux/sched/isolation.h:4,
                 from kernel/sched/MuQSS.c:34:
kernel/sched/MuQSS.c:230:19: note: previous declaration of ‘sched_smt_present’ was here
 EXPORT_SYMBOL_GPL(sched_smt_present);
                   ^
./include/linux/export.h:79:21: note: in definition of macro ‘___EXPORT_SYMBOL’
  extern typeof(sym) sym;      \
                     ^~~
kernel/sched/MuQSS.c:230:1: note: in expansion of macro ‘EXPORT_SYMBOL_GPL’
 EXPORT_SYMBOL_GPL(sched_smt_present);
 ^~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:304: kernel/sched/MuQSS.o] Error 1
make[1]: *** [scripts/Makefile.build:544: kernel/sched] Error 2
make: *** [Makefile:1051: kernel] Error 2

```

**Comment by trilean** [comment] 2019-03-03 13:22
See my [PR for MuQSS on 4.19](https://github.com/ckolivas/linux/pull/11). This fixes your issue!

**Comment by Techwolf** [comment] 2019-03-04 04:47
Thank you for the info. I did try the pull request against zen-4.19.26 and it failed. It is not a blocker for me as I noticed MuQSS 185 is in the 4.20 kernel branch and was planning on upgrading to that anyway.  I try not to jump 4.xx versions when upgrading to keep the .config file changes to a manageable level. :-) I went and tested/used without MuQSS and could not tell the difference, but only been using it a day.

```
patch --dry-run -p1 < 11.patch
checking file arch/x86/Kconfig
Hunk #1 succeeded at 1112 (offset -10 lines).
Hunk #2 succeeded at 1137 (offset -10 lines).
checking file kernel/livepatch/transition.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
4 out of 4 hunks ignored
checking file kernel/sched/MuQSS.c
Hunk #3 succeeded at 3833 with fuzz 2 (offset 3609 lines).
Hunk #4 FAILED at 258.
Hunk #5 FAILED at 299.
Hunk #6 FAILED at 345.
Hunk #7 FAILED at 753.
Hunk #8 FAILED at 1209.
Hunk #9 FAILED at 1228.
Hunk #10 FAILED at 1236.
Hunk #11 FAILED at 1333.
Hunk #12 FAILED at 1388.
Hunk #13 FAILED at 1417.
Hunk #14 FAILED at 1667.
Hunk #15 FAILED at 1698.
Hunk #16 FAILED at 1720.
Hunk #17 FAILED at 1736.
Hunk #18 succeeded at 5795 with fuzz 2 (offset 4001 lines).
Hunk #19 FAILED at 1804.
Hunk #20 FAILED at 2010.
Hunk #21 FAILED at 2071.
Hunk #22 FAILED at 2416.
Hunk #23 FAILED at 2580.
Hunk #24 succeeded at 6935 with fuzz 2 (offset 4075 lines).
Hunk #25 FAILED at 2907.
Hunk #26 FAILED at 3205.
Hunk #27 FAILED at 3225.
Hunk #28 FAILED at 3391.
Hunk #29 FAILED at 3920.
Hunk #30 FAILED at 4308.
Hunk #31 FAILED at 4359.
Hunk #32 FAILED at 4380.
Hunk #33 FAILED at 4390.
Hunk #34 FAILED at 4420.
Hunk #35 FAILED at 4604.
Hunk #36 FAILED at 4721.
Hunk #37 FAILED at 4737.
Hunk #38 FAILED at 5583.
Hunk #39 FAILED at 5600.
Hunk #40 FAILED at 5775.
Hunk #41 FAILED at 5869.
Hunk #42 FAILED at 5994.
Hunk #43 FAILED at 6076.
Hunk #44 FAILED at 6504.
Hunk #45 FAILED at 6522.
Hunk #46 FAILED at 6637.
Hunk #47 FAILED at 6648.
Hunk #48 FAILED at 6677.
Hunk #49 FAILED at 6887.
Hunk #50 succeeded at 7155 (offset 13 lines).
Hunk #51 succeeded at 7169 (offset 13 lines).
44 out of 51 hunks FAILED
checking file kernel/sched/MuQSS.h
checking file arch/alpha/Kconfig
checking file arch/powerpc/Kconfig
checking file arch/x86/Kconfig
Hunk #1 FAILED at 1059.
1 out of 1 hunk FAILED
checking file kernel/Kconfig.MuQSS
checking file kernel/sched/MuQSS.h
Hunk #1 succeeded at 730 (offset -36 lines).
```

**Comment by trilean** [comment] 2019-03-04 06:49
The patch doesn't apply because the fix is already in the tree: https://github.com/zen-kernel/zen-kernel/commit/1c4369e83c06a862de61b4893f4f75bcb380fdea

I've just tested. It compiles fine with MuQSS enabled. Are you sure you tried the latest version?

Generally, don't use `patch`. It's really dumb because it has no knowledge of a file's history. You should use `git am` if you apply patches exported from git. If that doesn't work try the `-3` (three-way) parameter.

**Comment by damentz** [comment] 2019-03-11 04:43
@Techwolf this should be fixed now.  I originally cherry-picked the export of sched_smt_present from 4.20/muqss, but it put it in the wrong location.  I moved it inside the ifdef when SMT is enabled.

Also, there were some other broken things caused by Paolo rebasing BFQ for 4.19, then adding new patches.  Without a complete resync, the BFQ code was completely borked.  You can see from the messy history and merges on 4.19/master that this was quite annoying to fix.

Anyway, it builds on my system now running GCC 8.2.1.  Let me know if this fixes your builds, otherwise I'll close this issue in a few days.

**Closed** 2019-03-19 02:31 UTC
