### ISSUE TITLE
Issue in swap usage

### ISSUE THREAD

**Issue by A404M** [zen-kernel/zen-kernel#356] opened 2024-08-13 21:57 UTC
After using linux-zen kernel for more than a year I realized that my system uses swap not in order that is optimized in any way.
I realized that my ram usage is always around 69% (yes I'm curious and that's funny) that was because when my ram gets around 50% usage the kernel will start using swappiness and when it gets to 69% nearly all other allocations would move some pages to swap until my swap gets nearly full and the kernel will fill ram again, but my swappiness was 1 and no matter value value it has, the kernel will always do that.
And as soon as I switched to vanilla linux kernel the problem went away.
I wonder if this functionality is intended or not?
I use the latest version of both kernels which comes in arch Linux repositories
Because I use linux-zen because waydroid only works with kernels which come with binder modules and linux-zen has it.
Thanks for your great efforts

**Comment by damentz** [comment] 2024-08-20 21:26
Is this impacting the responsiveness of your system?  Using swap in and of itself is not a problem unless it's actively causing issues with running applications.

We have some patches in our `zen-sauce` branch that affect swappiness.  For the most part, proactive compaction and other aggressive reclaim/compaction behavior is disabled since it disrupts foregrounds tasks too much under memory pressure.  What you're seeing instead is that memory is pushed to swap preemptively as a side effect.

**Comment by heftig** [comment] 2024-08-20 22:32
I do wonder what causes the ZEN kernel to swap so aggressively even with its default settings.

```
               total        used        free      shared     buffers       cache   available
Mem:             29G        8.7G         14G        127M        106K        6.6G         20G
Swap:            10G        2.3G        8.4G
Total:           39G         11G         22G
```

Though I don't remember how the vanilla kernel behaves.

**Comment by A404M** [comment] 2024-08-21 18:48
> Is this impacting the responsiveness of your system? Using swap in and of itself is not a problem unless it's actively causing issues with running applications.
> 
> We have some patches in our `zen-sauce` branch that affect swappiness. For the most part, proactive compaction and other aggressive reclaim/compaction behavior is disabled since it disrupts foregrounds tasks too much under memory pressure. What you're seeing instead is that memory is pushed to swap preemptively as a side effect.

Yes it does actually affect my system responsiveness a lot
Because I use 4 or 5 apps in foreground apps at the same time
I have more than enough RAM for them (16GB but the apps are not that heavy) but It does move my active memory to swap and that hurts performance in my case
I have been in Linux vanilla kernel after posting the issue till now and I really like it, the performance is much better here even when my whole ram and swap gets filled up

**Comment by damentz** [comment] 2024-08-21 20:41
There's a few commits that could be the problem:

1. https://github.com/zen-kernel/zen-kernel/commit/f61fea137cc64dc793ac3939a3f5eec5a7584951 - patches from https://github.com/kerneltoast to tame the memory subsystem.  They fixed real issues I was running into where as memory pressure increased, foreground applications would stall while compaction executed.  I think now what we're seeing is instead of compacting, pages are tossed into swap to be handled later.
2. https://github.com/zen-kernel/zen-kernel/commit/e33a55b58006b8c58d478f8cdfcce297e736a1d8 - disabling compaction of unevictable pages, possibly could be related?  This follows guidance from adjustments when PREEMPT_RT is turned on in ifdef macros.  Restore with **sudo sysctl -w vm.compact_unevictable_allowed=1**
3. https://github.com/zen-kernel/zen-kernel/commit/47aa9995d6c9877a946f407137417521cc6a9963 - proactive compaction causes stalls in foreground applications if set to aggressive.  Even at light settings I had problems with it so we use kerneltoast's patch.  You can restore the default with **sudo sysctl -w vm.compaction_proactiveness=20**.
4. https://github.com/zen-kernel/zen-kernel/commit/627d13a7efb4d9ee1ac282017d0fcb5952b9108a - disabling watermark boosting is similar in effect of disabling proactive compaction.  Restore to default with **sudo sysctl -w vm.watermark_boost_factor=15000**
5. https://github.com/zen-kernel/zen-kernel/commit/1b4743e952cfd1fa00e7c438d7e61ed18f5c5800 - protecting cache of data accessed in the last second, probably not related but you can tune in the value in **/sys/kernel/mm/lru_gen/min_ttl_ms** and restore it to **0** for testing.

@A404M would you be able to try testing the tunables to see if they're related?  Worst case it's the first commit I mentioned.  Speaking of which, we've been rebasing these patches for a while now, might be worth seeing if anything has changed in kerneltoast's current branch: https://github.com/kerneltoast/kernel_x86_laptop/commits/v6.10-sultan/

**Comment by damentz** [comment] 2024-09-29 16:30
@A404M have you had a chance to tweak any of the files/sysctls I referenced?

**Comment by A404M** [comment] 2024-10-03 13:51
@damentz I haven't had the time to try it
But tomorrow is my day off, I will try it then
Sorry for the delay

**Comment by pckotzer** [comment] 2024-10-06 00:56
I have with the zen kernel almost not functinally swapiness value, its just didnt worked, i have set it to 200, but then after i used kerneltoast defconfig and all he patches without the thermal stuff, swapiness vaule worked. And also i build Android and ram is exactly that whats needed sometimes on mass. Just want to say after his arch_defconfig and all his patches. The swap or zram i use is much better now. I dont have to wait now that long when zram is used. Normally i would have to wait longer in the default kernel settings, When android.pb build starts, this is the part which i dont like cause normally it would take a long time, but now after the patches and the defconfig its much better. I dont have to wait that long now. It clearly improved something. It was the kernel_86_leptop from kerneltoast aka sultan

**Comment by damentz** [comment] 2024-10-22 16:11
Maybe the issue was MG-LRU?  A patch just arrived in v6.11.5 that fixes an early OOM under swap pressure: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.11.5&id=8d4f2d8ca9e29fe7461734dab1aa50a89a7768bd

**Comment by pckotzer** [comment] 2024-10-26 20:37
Installing liqu kernel will also work @damentz ?

**Comment by damentz** [comment] 2024-10-27 00:48
> Installing liqu kernel will also work @damentz ?

Yes, Liquorix has the same configuration for memory as Zen Kernel.

**Comment by pckotzer** [comment] 2024-10-28 19:55
I tested and it behaves like nothing has happend, its almost too late for swaping, on my self build zenkernel, also with latest changes it dont does that. I think this is something relevant in the defconfig, but for now i dont know which exactly

**Comment by damentz** [comment] 2024-10-28 20:09
@pckotzer can you try disabling MG-LRU?  You can make the change realtime in /sys/kernel/mm/lru_gen I believe, or in the folder above it.

**Comment by pckotzer** [comment] 2024-10-28 20:34
I dont find that option in /sys/kernel/mm/lru_gen, have only: ksm  swap  transparent_hugepage in mm folder.
Right now on my self build, i have just used some stuff of sultans x86 kernel. In the normal kernel i tested a moment ago it also stutters when here its fine, i think its worth looking in the defconfig, i just mergerd everything that make sense too me and now its good, he knows how to toast a kernel haha

**Comment by damentz** [comment] 2024-10-28 21:07
So your self build isn't using MG-LRU?  What I was asking is on a Zen or Liquorix kernel, set **/sys/kernel/mm/lru_gen/enabled** to "n" and see if you can reproduce the issues you're running into.

You can also adjust **/sys/kernel/mm/lru_gen/min_ttl_ms** to **0** to reproduce stock.

What I'm trying to figure out is if MG-LRU itself is an issue here as you don't enable it with @kerneltoast's.  If it is, we need to figure out what's going on with it.

**Comment by kerneltoast** [comment] 2024-10-28 22:55
> So your self build isn't using MG-LRU? What I was asking is on a Zen or Liquorix kernel, set **/sys/kernel/mm/lru_gen/enabled** to "n" and see if you can reproduce the issues you're running into.
> 
> You can also adjust **/sys/kernel/mm/lru_gen/min_ttl_ms** to **0** to reproduce stock.
> 
> What I'm trying to figure out is if MG-LRU itself is an issue here as you don't enable it with @kerneltoast's. If it is, we need to figure out what's going on with it.

FYI, I disable mglru in my laptop kernel defconfig.

**Comment by damentz** [comment] 2024-10-30 14:53
And what if you try setting **/sys/kernel/mm/lru_gen/enabled** to **n**?

**Comment by pckotzer** [comment] 2024-10-30 15:00
Nope, still bad

**Comment by damentz** [comment] 2024-11-08 18:37
Kernel v6.11.7 includes a lot of fixes to the memory subsystem, especially to MG-LRU.  Please give it a try once a Liquorix or Zen Kernel build is available based on this version.

**Comment by pckotzer** [comment] 2024-11-08 18:43
Will try now, also about the swap, could it be that i dont use zswap? In the defconfig i dont use it. Sultan say it is only useful if the device is used to swap is faster, which is unlikely so it gets disabled.

**Comment by damentz** [comment] 2024-11-08 18:57
> Will try now, also about the swap, could it be that i dont use zswap? In the defconfig i dont use it. Sultan say it is only useful if the device is used to swap is faster, which is unlikely so it gets disabled.

That could be it, you can add `zswap.enabled=0` to your kernel boot parameters and see how your system behaves.

Also, in both Liquorix and Zen Kernel configs, **CONFIG_ZSWAP_DEFAULT_ON=y** is set, so that could be the culprit.

**Comment by pckotzer** [comment] 2024-11-08 19:17
@damentz Now its good, no stutters anymore

**Comment by damentz** [comment] 2024-11-08 21:02
@heftig looks like we should turn off zswap by default as it hinders responsiveness under load.

**Comment by damentz** [comment] 2024-11-11 15:39
@A404M next linux-zen release will reapply a patch we reverted and disable zswap compressed cache by default.  Can you also confirm that **zswap.enable=0**  helps on your system?

**Comment by damentz** [comment] 2024-11-17 17:15
Ok, I'm going to mark this as resolved.  @A404M if this didn't help and you're still having problems, let us know and we'll reopen.

**Comment by A404M** [comment] 2024-11-17 18:03
> Ok, I'm going to mark this as resolved.  @A404M if this didn't help and you're still having problems, let us know and we'll reopen.

I'm sorry for not being active here
I have some problems at job and I can't take a break even for a day to do the works you mentioned.
I guess the best thing is to close this issue and I will recheck when I got free time.
I'm sorry again for not answering😞

**Comment by ReillyBrogan** [comment] 2024-11-20 17:17
Has anyone reached out to the kernel zswap maintainers about this behavior?

**Comment by damentz** [comment] 2024-11-21 16:45
> Has anyone reached out to the kernel zswap maintainers about this behavior?

Not that I'm aware of, but for whoever reports, a script or series of instructions to reproduce the issue reliably will be important.  More importantly you want whatever utility you're running to have numbers that indicate the "stutter" and "jank", otherwise it's hard for maintainers to prioritize a solution.

**Comment by damentz** [comment] 2024-12-05 21:59
Reopening while we experiment with different methods to prevent excessive swapping.

**Comment by damentz** [comment] 2024-12-10 14:24
This is resolved by https://github.com/zen-kernel/zen-kernel/commit/856c3874536c066b0f02b38b24092610692959ff, where lru_gen_min_ttl parameter was causing early OOMs and excessive swapping.  Proactive compaction restore to default will also stay while we determine a non-zero value for interactive systems.

**Closed by damentz** 2024-12-10 14:24 UTC
