### ISSUE TITLE
Request to Update Zen Kernel Wiki tab or README file 

### ISSUE THREAD

**Issue by amayra** [zen-kernel/zen-kernel#343] opened 2024-03-07 12:27 UTC
I hope this message finds you well. I am a user of the Zen Kernel and I've noticed that the information on the wiki page may need some updating to reflect the latest features, optimizations, and improvements in the kernel. I believe that updating the wiki page would be beneficial for both current users and newcomers who are interested in learning more about the Zen Kernel.

links : 

https://github.com/zen-kernel/zen-kernel/wiki
https://github.com/zen-kernel/zen-kernel/blob/6.7/main/README

**Comment by damentz** [comment] 2024-03-25 00:57
This is technically a duplicate of #30, but would you be offering to maintain the wiki on our behalf?

**Comment by amayra** [comment] 2024-04-06 05:02
!I'd be happy to help maintain the wiki for the Zen Kernel project. 

Would it be acceptable to utilize AI assistance in maintaining the wiki for the Zen Kernel project? I believe AI tools could streamline the process and help ensure accuracy and consistency in the documentation.

I plan to make updates to the wiki or README file and submit them as pull requests.

**Comment by amayra** [comment] 2024-04-06 05:02
> This is technically a duplicate of #30, but would you be offering to maintain the wiki on our behalf?

I will be happy to help maintain the wiki for the Zen Kernel project.

Would it be acceptable to utilize AI assistance in maintaining the wiki for the Zen Kernel project? I believe AI tools could streamline the process and help ensure accuracy and consistency in the documentation.

I plan to make updates to the wiki or README file and submit them as pull requests.

**Comment by CuteistFox** [comment] 2024-04-28 01:04
> Would it be acceptable to utilize AI assistance in maintaining the wiki for the Zen Kernel project? I believe AI tools could streamline the process and help ensure accuracy and consistency in the documentation.'

AI says: "Zen kernel is a new type of popcorn kernel that has optimisations desined for interactive use and stuff"

**Closed** 2024-05-04 05:11 UTC
