### ISSUE TITLE
MuQSS is missing 2 lines used by mgLRU

### ISSUE THREAD

**Issue by thubble** [zen-kernel/zen-kernel#236] opened 2021-08-14 15:46 UTC
I don't run Zen/Liquorix but rather my own custom kernel that includes many of the same patches, including mgLRU and MuQSS, and I often compare my own patchset to Zen to see if I'm missing anything.

One thing I noticed is that Zen is missing 2 lines in `sched/MuQSS.c` that were added to `sched/core.c` by mgLRU:
- https://github.com/zen-kernel/zen-kernel/blob/5394f2eaa89b8d5979fe421434b1d6b2372ae443/kernel/sched/core.c#L4332 
- https://github.com/zen-kernel/zen-kernel/blob/5394f2eaa89b8d5979fe421434b1d6b2372ae443/kernel/sched/core.c#L7607

These 2 functions (context_switch() and idle_task_exit()) are largely unchanged between CFS and MuQSS, so I just added those 2 lines to the equivalent places in MuQSS.c, and it seems to be working fine. I haven't tried without these lines.

I don't know enough about mgLRU to know what the effect of these missing lines would be, but they appear to give per-process data or hints to mgLRU, so I suspect missing them could cause issues. @yuzhaogoogle would maybe know more?

-----------

One other thing I noticed is this scheduler change MuQSS port: https://github.com/zen-kernel/zen-kernel/commit/63ae1c65c7625201d641b9a8227c072c671be7b6

I missed this in my own 5.13 port of MuQSS and was about to add it, but I realized that it doesn't actually have any effect, because MuQSS doesn't ever call `is_cpu_allowed()` - it uses the CPU masks directly. I tried to find a way to port that change, but gave up because MuQSS is quite different from CFS in terms of how it handles finding suitable CPUs for processes (which isn't surprising). My first thought was to change how it uses the masks, but wasn't confident due to the differences - e.g. CFS uses `cpu_online_mask` for kthreads whereas MuQSS uses `cpu_all_mask`.

It looks like this change is one of several scheduler changes, mostly around kthreads, that haven't been ported to MuQSS - though I'm not 100% sure they need to be. I debated opening another bug about this, but it's probably something that Con Kolivas will need to take a look at once he's back in action.

**Comment by damentz** [comment] 2021-08-14 16:46
Wow, good catch @thubble!  Normally when porting I only pay attention to updates to mainline and stable releases.  And surprisingly, MG-LRU appears to work just fine without the two additions to `core.c`.  Either way, I added the two changes through a macro so MuQSS can still be built independently in the 5.13/muqss branch, or in-case someone takes our patches and wants to use MuQSS on their own kernel distribution without MG-LRU.

As for https://github.com/zen-kernel/zen-kernel/commit/63ae1c65c7625201d641b9a8227c072c671be7b6, I always side with syncing with mainline first over any particular code we can omit in MuQSS.  Even if the function does nothing, it lines up with what's coded in mainline so it makes future endeavors to sync code easier and more straightforward.  And with these changes, suspend + resume still work great across a work and personal laptop of mine, so I'm assuming everything the code was intended to do still works.

**Comment by damentz** [comment] 2021-08-14 17:47
Marking this as resolved, system boots and runs fine with the two added lines.

**Closed by damentz** 2021-08-14 17:47 UTC
