### ISSUE TITLE
Hard freeze on amdgpu with versions after 6.6.10

### ISSUE THREAD

**Issue by Kommynct** [zen-kernel/zen-kernel#340] opened 2024-02-07 21:53 UTC
Unfortunately I cannot upgrade as my system becomes unusable, it completely freezes regularly

I have an amdgpu, 6650xt and a AMD Ryzen 9 3900XT processor.

appears to be a much worse version of #338

**Comment by damentz** [comment] 2024-02-07 22:24
Can you confirm if stock / mainline has the same issue?

**Comment by Kommynct** [comment] 2024-02-08 01:28
Just tested that, it does have the same issue, where should I report this?

**Comment by damentz** [comment] 2024-03-25 00:52
I think this would be the best place to report: https://gitlab.freedesktop.org/drm/amd/-/issues, but otherwise since this issue effects upstream, closing this out since we're not the best place to report.

If you get are still affected on current kernels and manage to receive an early patch that fixes your issue, notify us and we'll add it in.

**Closed by damentz** 2024-03-25 00:52 UTC

**Comment by DiegoNogueiraDev** [comment] 2026-02-21 20:09
I've documented a 100% reproducible case of this on AMD Barcelo (Ryzen 7 5825U) with kernel 6.17 — 15/15 boots crashed, kernel 6.8 stable. Full data and methodology: https://github.com/DiegoNogueiraDev/kernel-617-amdgpu-freeze-bug
