### ISSUE TITLE
System freezing issue in AMD CPU's

### ISSUE THREAD

**Issue by RajrupDasid** [zen-kernel/zen-kernel#286] opened 2022-06-22 03:54 UTC
AMD Ryzen 2500u cpu
12 GB RAM 500GB SSD Laptop
very often system freezing issue going on. And to be sure it's only for AMD cpus 
when I was in 5.17 there was freezing issue but not very often like right now.
OS-Arch linux pure
WM- Xmonad latest
use-cases - Programming

**Comment by damentz** [comment] 2022-06-22 11:24
This is a duplicate of https://github.com/zen-kernel/zen-kernel/issues/285, closing.

**Closed** 2022-06-22 11:25 UTC
