### ISSUE TITLE
incorrect gpu power and clocks RX7600

### ISSUE THREAD

**Issue by Avverryyy** [zen-kernel/zen-kernel#330] opened 2023-09-16 03:04 UTC
as it is a newer card I have waited till kernel 6.5 for proper gpu support for my RX7600 and have had some issues such as getting the ability to overclock resolved but have a more prominent problem remaining. In corectl and in the appropriate files that tell my gpu how to perform all my values are incorrect. my 165 watt gpu is running at 135 watts with the slider maxed and my core and memory clocks are way under stock operating specs of my card. if anyone could help me it would be greatly appreciated
![image](https://github.com/zen-kernel/zen-kernel/assets/145176324/a0a66f0a-4428-4ffa-937b-e46e4b091eac)

**Comment by damentz** [comment] 2023-09-17 18:19
Can you reproduce on a stock 6.5 kernel?

**Comment by Avverryyy** [comment] 2023-09-17 18:37
when 6.5 mainline first came out it allowed me to get 5% overclock which is correct but over the 135 Watt value and I have not tried since. I just installed the stock 6.5 kernel and the probably does seem persistent. if this is a matter outside of the zen kernel i understand but any help on who to contact or what may fix the problem would be greatly appreciated.
![image](https://github.com/zen-kernel/zen-kernel/assets/145176324/bfbfa05c-d09d-41ac-9d81-ff26a57793be)

**Comment by damentz** [comment] 2023-09-17 19:53
This is probably the best place to report your issue: https://gitlab.freedesktop.org/drm/amd/-/issues/

I also recommend you look for related issues since you might find a workaround from similar reports.

I'll close this out since we're really not the best place to handle upstream issues.

**Closed by damentz** 2023-09-17 19:53 UTC

**Comment by HugKitten** [comment] 2024-04-06 16:36
Just noticed, my power limits are wrong too.

**Comment by Avverryyy** [comment] 2024-04-06 18:42
> Just noticed, my power limits are wrong too.

If you are on 6.7+ kernel try using a gpu tuning tool called lact it seems to have a work around that has not been incorporated into corectrl or similar softwares. The power limit may seem low yet but I believe it is core power not total board power so you should have a fully functional card.
