### ISSUE TITLE
ddcutil dumps the core under 6.8.2.zen

### ISSUE THREAD

**Issue by notorand-it** [zen-kernel/zen-kernel#347] opened 2024-03-28 17:19 UTC
It is ddcutil v2.1.4 but it works flawlessly under linux-zen 6.8.1.zen.
This is the dumped core.
[ddcutil.core.gz](https://github.com/zen-kernel/zen-kernel/files/14793313/ddcutil.core.gz)

OS: ArchLinux
Architecture: x86-64
Kernel: linux-zen (6.8.1.zen1-1 -> 6.8.2.zen1-1)

Logs from dmesg:
```
[ 7011.672432] scsi 1:0:0:0: Direct-Access              PHILIPS          8.07 PQ: 0 ANSI: 4
[ 7011.676135] sd 1:0:0:0: [sdb] 61440000 512-byte logical blocks: (31.5 GB/29.3 GiB)
[ 7011.677397] sd 1:0:0:0: [sdb] Write Protect is off
[ 7011.677403] sd 1:0:0:0: [sdb] Mode Sense: 23 00 00 00
[ 7011.678183] sd 1:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 7011.684534]  sdb: sdb1
[ 7011.684606] sd 1:0:0:0: [sdb] Attached SCSI removable disk
[ 7021.028460] ddcutil[9077]: segfault at 0 ip 00007f6f5925615c sp 00007ffd7c6cef28 error 4 in libc.so.6[7f6f59110000+15b000] likely on CPU 3 (core 3, socket 0)
[ 7021.028471] Code: ff ff 48 89 f8 0f bc c9 f3 a4 c3 0f 1f 00 f3 0f 1e fa 89 f8 62 a1 fd 00 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 24 01 00 00 <62> f1 7d 20 74 07 c5 fb 93 c0 85 c0 74 16 0f bc c0 c3 66 90 0f bc
```

If you need more details, just ask.

**Comment by heftig** [comment] 2024-03-28 18:21
It's probably an upstream issue. Does the same happen with the arch kernel?

**Comment by notorand-it** [comment] 2024-03-29 07:50
First of all, I am attaching here the needed debuginfo file.
[5f402fab615a2f58da30db4eba37fbd4abd412e5-debuginfo.gz](https://github.com/zen-kernel/zen-kernel/files/14801206/5f402fab615a2f58da30db4eba37fbd4abd412e5-debuginfo.gz)

**Comment by notorand-it** [comment] 2024-03-29 08:11
With latest kernel `Linux version 6.8.2-arch2-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000`  I don't get the core dump: neither `sudo dmesg`  nor `coredumpctl` is showing it.

Nonetheless, the `scsi` device pops up in logs after about 50 seconds from insertion, `lsblk` DOESN'T show it and (of course) auto-mount doesn't kick in. It happens within 1 or 2 seconds with `6.8.1.zen1-1` kernel.

**Comment by loqs** [comment] 2024-04-10 15:01
I believe the issue in ddcutil is https://github.com/rockowitz/ddcutil/issues/405.

**Comment by damentz** [comment] 2024-06-26 00:12
Closing issue since this is confirmed upstream.

**Closed by damentz** 2024-06-26 00:12 UTC
