### ISSUE TITLE
No wifi 5.14.3-zen1

### ISSUE THREAD

**Issue by Pross** [zen-kernel/zen-kernel#240] opened 2021-09-13 11:44 UTC
I was using 5.14.1-zen1 that seemed fine, upgraded to 5.14.3-zen1 last night and I have no wifi, also rebooting takes agaes or hangs.

[dmesg.txt](https://github.com/zen-kernel/zen-kernel/files/7153947/dmesg.txt)

[config.txt](https://github.com/zen-kernel/zen-kernel/files/7153949/config.txt)

**Comment by heftig** [comment] 2021-09-15 11:55
MuQSS is known to be broken.

**Comment by Pross** [comment] 2021-09-15 13:07
Disabling muqss boots with no issues.

**Comment by heftig** [comment] 2021-09-15 13:11
Duplicate of #241.

**Closed by heftig** 2021-09-15 13:11 UTC
