### ISSUE TITLE
Too much heating issue under normal usages

### ISSUE THREAD

**Issue by rajrupdasofficial** [zen-kernel/zen-kernel#361] opened 2024-10-02 09:41 UTC
Too much heating issue after upgrading to kernel version 6.11.
After even changing the thermal paste still temperature is going very high

Current temperature - 78 deg C.
Fan speed - 4100 all time.
this issue facing under normal circumstances.
please fix the issue ASAP.
I can assure you there is no hardware issue or sensors issue.
 
Processor - Ryzen 2500U
RAM - 16GB
SSD 1TB

**Comment by sentakuhm** [comment] 2024-10-02 10:41
After updating to linux-zen 6.11, when open CS2 sometimes crush and exit at once and sometime take a some time playing then crush and exit.
dmesg log:
```
AsyncIOService[5286]: segfault at 0 ip 00007e5852f84e86 sp 00007e584725dbd0 error 6 in libtier0.so[184e86,7e5852ec1000+305000] likely on CPU 12 (core 4, socket 0)
```
journalctl:
```
Oct 02 11:18:21 MortyRYX systemd-coredump[5351]: Process 5260 (cs2) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 5286:
                                                 #0  0x00007e5852f84e86 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so + 0x184e86)
                                                 #1  0x00007e5852f8773f n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so + 0x18773f)
                                                 #2  0x00007e5852f9e4d4 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so + 0x19e4d4)
                                                 #3  0x00007e58467f0c89 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x1f0c89)
                                                 #4  0x00007e58467f1215 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x1f1215)
                                                 #5  0x00007e58467f61c3 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x1f61c3)
                                                 #6  0x00007e584666c7f0 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x6c7f0)
                                                 #7  0x00007e584665d8f8 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5d8f8)
                                                 #8  0x00007e584665ea27 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5ea27)
                                                 #9  0x00007e584665cfae n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5cfae)
                                                 #10 0x00007e584665d164 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so + 0x5d164)
                                                 #11 0x00007e5852fd2ed3 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so + 0x1d2ed3)
                                                 #12 0x00007e5852fd41d7 n/a (/home/sentaku/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so + 0x1d41d7)
                                                 #13 0x00007e585521f39d n/a (/run/host/usr/lib/libc.so.6 + 0x9439d)
                                                 #14 0x00007e58552a449c n/a (/run/host/usr/lib/libc.so.6 + 0x11949c)
                                                 ELF object binary architecture: AMD x86-64
```

**Comment by damentz** [comment] 2024-10-02 19:54
Have you guys confirmed stock is affected or not?  Also, please provide the output of `sudo cpupower frequency-info` and `inxi -C`.

**Comment by rajrupdasofficial** [comment] 2024-10-03 14:49
@damentz please check these data which you wanted -
this data is showing when i have opened firefox and on it open github to reply you 

### sudo cpupower frequency-info
analyzing CPU 7:
  driver: acpi-cpufreq
  CPUs which run at the same hardware frequency: 7
  CPUs which need to have their frequency coordinated by software: 7
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 1.60 GHz - 2.00 GHz
  available frequency steps:  2.00 GHz, 1.70 GHz, 1.60 GHz
  available cpufreq governors: conservative ondemand userspace powersave performance schedutil
  current policy: frequency should be within 1.60 GHz and 2.00 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency: 2.00 GHz (asserted by call to hardware)
  boost state support:
    Supported: no
    Active: no
    Boost States: 0
    Total States: 3
    Pstate-P0:  2000MHz
    Pstate-P1:  1700MHz
    Pstate-P2:  1600MHz

#### sudo inxi -C
CPU:
  Info: quad core model: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
   bits: 64 type: MT MCP cache: L2: 2 MiB
  Speed (MHz): avg: 1600 min/max: 1600/2000 
cores: 1: 1600 
2: 1600 
3: 1600
4: 1600 
5: 1600 
6: 1600 
7: 1600 
8: 1600

#### current cpu temperature -
sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +36.0°C  

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     2900 RPM

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.52 V  
power1:       11.55 W  

amdgpu-pci-0300
Adapter: PCI adapter
vddgfx:           N/A  
vddnb:            N/A  
edge:         +75.0°C  

jc42-i2c-1-18
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +39.0°C  (low  =  +0.0°C)                  ALARM (HIGH, CRIT)
                       (high =  +0.0°C, hyst =  +0.0°C)
                       (crit =  +0.0°C, hyst =  +0.0°C)

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +75.5°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +75.0°C  


Sensors are ok .
I have changed thermal paste but same issue . it dropped temps by 15 degrees because previously before changing  temps going upto 99degrees which is impossible . And the problem is surely with kernel.

I tried to set offset into the config but every time i tried - it shown syntax error .

Tell me how to set offset in k10temp.conf file 

And when are you releasing the fix?
Please fix the bug ASAP

**Comment by rajrupdasofficial** [comment] 2024-10-03 15:38
I know man I am also a developer and rust programmer I know this will going to take time . please take time and apply a permanent fix . My laptop is not working good on this matter I want tell that after the issue appear I check with a laptop repair shop and paid some good money , i first thought my battery was not ok but they told everything is fine. 
There is no shortage or anything on motherboard.
Then where is the issue ? Possibly with the software and that is what happening.
I know you people are just maintainers and you have o obligation to help you with my issue.
I am accepting this.
Right now is not possible but in future possible?

**Comment by damentz** [comment] 2024-10-03 15:44
@rajrupdasofficial I think there's a lot more you need to research and explore on your system before creating an issue for Zen Kernel.

This is not a forum for tech support but for genuine issues that are unique to Zen Kernel, and you have not demonstrated that's the case.

Closing issue out.

@sentakuhm if you can't reproduce this issue on the stock kernel, feel free to open a new issue for yours.

**Closed by damentz** 2024-10-03 15:44 UTC

**Comment by rajrupdasofficial** [comment] 2024-10-03 16:18
@damentz  Do you read and understand English?  I have clearly mentioned I already shown my device to a professional repair shop to fix the issue , if anything related to hardware and motherboard. 
I also mentioned I paid for the checkup and repair and they told that they didnot found any issues on motherboard .
You people are making mistakes and blaming on us that we are doing something wrong. I should never choose zen kernel or Linux first of all. 
I also want to become a maintainer in future and that is why I am learning and programming rust. 
You people are just toxic and disgusting. I am sorry for saying this .

**Comment by sentakuhm** [comment] 2024-10-03 16:24
@damentz i'll try install stock kernel and inform you.

**Comment by sentakuhm** [comment] 2024-10-04 11:00
@damentz its `ryzen_smu` issue i was using it to undervolt my cpu removed it and everything seems to be ok.

**Comment by rajrupdasofficial** [comment] 2024-10-10 16:05
My system problem has been resolved with switching to the stable LTS kernel.
